"""Render a CLEAR (imaging) stage-2 :class:`Recipe` into a per-frame runner script.

The generated script is the explicit, editable reduction chain (step parameters
live in the calls, not the recipe). At run time it loads the NooBox, probes every
input-stage book, reduces the selected ones through the chain, saves each
``save_as`` product with explicit lineage, then writes the manifest.

When the ``fixed_pattern`` step is enabled the script gains a pass 0: before the
per-frame loop it groups the selected rate frames by detector and builds (or
loads a cached) one fixed-pattern template per detector, which the per-frame step
then amplitude-fits and subtracts before 1/f and flat-fielding.

The source is built by sentinel replacement (not ``str.format``) so the
brace-heavy generated code needs no escaping, and validated with
:func:`ast.parse` before it is returned.
"""

import ast

from noobfriend.cli.reduce._recipe import Recipe, ordered
from noobfriend.cli.reduce._reduce_clear_stage2 import CHAIN

#: Pass-0 helper injected when the fixed_pattern step is enabled. Streams each
#: frame's residual to disk and memory-maps them into the cross-frame median so
#: peak RAM stays bounded regardless of how many exposures a detector has.
_FIXED_PATTERN_HELPER = '''def _build_fixed_pattern_templates(box) -> dict:
    """Build (or load cached) one per-detector fixed-pattern template (pass 0).

    Groups the selected rate frames by detector, streams each frame's
    source-masked residual to disk, and median-combines them as memory maps
    (bounded peak RAM) into one template per detector, cached under
    FIXED_PATTERN_DIR for reuse on re-runs.
    """
    FIXED_PATTERN_DIR.mkdir(parents=True, exist_ok=True)
    by_detector: dict[str, list] = {}
    for book in box.select(stage=STAGE_IN):
        if not book.is_probed:
            book = book.probe()
        if _keep(book):
            by_detector.setdefault(book.detector, []).append(book)
    templates: dict[str, object] = {}
    for detector, books in by_detector.items():
        cache = FIXED_PATTERN_DIR / f"{detector}.npy"
        if cache.exists():
            templates[detector] = np.load(cache)
            continue
        residual_paths: list = []
        for book in track(books, f"Fixed-pattern residuals {detector}"):
            model = _open_model(book.read_bytes())
            residual = fixed_pattern_residual(model.data, model.dq).astype("float32")
            model.close()
            path = FIXED_PATTERN_DIR / f"_residual_{detector}_{len(residual_paths):04d}.npy"
            np.save(path, residual)
            residual_paths.append(path)
        template = combine_fixed_pattern([np.load(p, mmap_mode="r") for p in residual_paths])
        np.save(cache, template)
        for path in residual_paths:
            path.unlink()
        templates[detector] = template
    return templates'''

_TEMPLATE = '''"""Reduction runner generated by `noobfriend reduce gen` -- edit step params here.

Run where the NooBox product locations open locally (e.g. on the data server):

    python <this_script.py>

The updated manifest goes to OUTPUT_NOOBOX below (set from the recipe); when it
is None the input manifest (NOOBOX_PATH) is updated in place. Give each parallel
shard its own output_noobox in the recipe and merge them afterwards.
"""

from __future__ import annotations

import fnmatch
import os
import tempfile
from pathlib import Path

from noobfriend.core.env import get_settings, stage_path_var

__MUTE_BLOCK__get_settings()  # load .env into os.environ (CRDS, stage paths, NOOBOX_PATH)

from noobfriend.core.display import track
from noobfriend.core.io import write_bytes
from noobfriend.navigation import NooBook, NooBox
__REDUCTION_IMPORT__
import jwst.datamodels as _dm
__JWST_IMPORTS__

STAGE_IN = "__STAGE_IN__"
SELECT = __SELECT__
OUTPUT_NOOBOX = __OUTPUT_NOOBOX__
__FIXED_PATTERN_CONST__

def _keep(book) -> bool:
    """Whether ``book`` matches the recipe selection (scalar pupil/filter/detector)."""
    for field, crit in SELECT.items():
        value = getattr(book, field)
        if isinstance(crit, str):
            if value is None or not fnmatch.fnmatch(str(value), crit):
                return False
        elif crit is not None and value not in crit:
            return False
    return True


def _out_location(book, stage: str) -> str:
    """Compose <NOOB_SERVER>:<STAGE_<stage>_PATH>/<exposure-stem>_<stage>.fits.

    Remote (a ``host:path`` spec) when NOOB_SERVER names a host, so write_bytes
    uploads over SSH; local otherwise. Parent directories are created by
    write_bytes, not here.
    """
    directory = os.getenv(stage_path_var(stage))
    if directory is None:
        raise RuntimeError(f"{stage_path_var(stage)} is unset in the environment.")
    stem = os.path.basename(book.location)
    for ext in (".fits.gz", ".fits"):
        if stem.endswith(ext):
            stem = stem[: -len(ext)]
            break
    stem = stem.rsplit("_", 1)[0]  # drop the input product suffix
    host = get_settings().server_host()
    base = f"{host}:{directory}" if host else directory
    return base.rstrip("/") + "/" + f"{stem}_{stage}.fits"


def _open_model(raw: bytes):
    """Open a JWST datamodel from bytes without passing a deprecated HDUList."""
    with tempfile.NamedTemporaryFile(suffix=".fits", delete=False) as handle:
        tmp = handle.name
        handle.write(raw)
    try:
        return _dm.open(tmp)
    finally:
        os.unlink(tmp)


def _save_bytes(model, stage: str) -> bytes:
    """Serialise ``model`` to bytes through a temp file (jwst save needs a path)."""
    with tempfile.NamedTemporaryFile(suffix=f"_{stage}.fits", delete=False) as handle:
        tmp = handle.name
    try:
        model.save(tmp)
        return Path(tmp).read_bytes()
    finally:
        os.unlink(tmp)

__FIXED_PATTERN_HELPER__
def main(output_noobox_path: str | None = None) -> None:
    box = NooBox.load()
    out_box = box if output_noobox_path is None else NooBox()
__FIXED_PATTERN_BUILD__
    for book in track(box.select(stage=STAGE_IN), f"Reducing {STAGE_IN}"):
        if not book.is_probed:
            book = book.probe()
            out_box.add(book)  # back-fill the probed copy into the manifest
        if not _keep(book):
            continue
        # bytes via the NooBox store: remote-capable and reuses the probe fetch.
        model = _open_model(book.read_bytes())
        parent = book
__BODY__
        model.close()
    out_box.save(output_noobox_path)


if __name__ == "__main__":
    main(OUTPUT_NOOBOX)
'''


def render(recipe: Recipe) -> str:
    """Return the runner-script source for ``recipe`` (validated by ``ast.parse``)."""
    steps = ordered(CHAIN, recipe.steps)
    fixed_on = any(spec.name == "fixed_pattern" for spec, _ in steps)

    custom_names = {spec.custom for spec, _ in steps if spec.custom}
    if fixed_on:
        custom_names |= {
            "combine_fixed_pattern",
            "fixed_pattern_residual",
            "subtract_fixed_pattern",
        }
    reduction_import = (
        f"from noobfriend.reduction import {', '.join(sorted(custom_names))}"
        if custom_names
        else ""
    )
    jwst_imports = sorted(
        {
            f"from {spec.jwst.rsplit('.', 1)[0]} import {spec.jwst.rsplit('.', 1)[1]}"
            for spec, _ in steps
            if spec.jwst
        }
    )

    select = {
        field: value
        for field in ("pupil", "filter", "detector")
        if (value := getattr(recipe.select, field)) is not None
    }

    mute_block = (
        "import logging\n\n"
        "logging.disable(logging.WARNING)  "
        "# silence jwst / CRDS / stpipe INFO+WARNING chatter\n\n"
        if recipe.mute_jwst
        else ""
    )

    if fixed_on:
        fp_const = f"import numpy as np\n\nFIXED_PATTERN_DIR = Path({recipe.clear.template_dir!r})\n"
        fp_helper = _FIXED_PATTERN_HELPER
        fp_build = "    templates = _build_fixed_pattern_templates(box)"
    else:
        fp_const = fp_helper = fp_build = ""

    body: list[str] = []
    for spec, cfg in steps:
        if spec.name == "fixed_pattern":
            body.append(
                "model.data, model.err, model.dq = subtract_fixed_pattern("
                "model.data, model.err, model.dq, templates[book.detector])"
            )
        elif spec.custom:
            body.append(
                f"model.data, model.err, model.dq = "
                f"{spec.custom}(model.data, model.err, model.dq)"
            )
        else:
            cls = spec.jwst.rsplit(".", 1)[1]
            body.append(f"model = {cls}.call(model)")
        if cfg.save_as:
            stage = cfg.save_as
            body += [
                f"_loc = _out_location(book, {stage!r})",
                f"_raw = _save_bytes(model, {stage!r})",
                "write_bytes(_loc, _raw)",
                f"parent = NooBook.from_file(_loc, {stage!r}, parents=[parent], raw=_raw)",
                "out_box.add(parent)",
            ]

    source = (
        _TEMPLATE.replace("__REDUCTION_IMPORT__", reduction_import)
        .replace("__JWST_IMPORTS__", "\n".join(jwst_imports))
        .replace("__MUTE_BLOCK__", mute_block)
        .replace("__STAGE_IN__", recipe.select.stage)
        .replace("__SELECT__", repr(select))
        .replace("__OUTPUT_NOOBOX__", repr(recipe.output_noobox))
        .replace("__FIXED_PATTERN_CONST__", fp_const)
        .replace("__FIXED_PATTERN_HELPER__", fp_helper)
        .replace("__FIXED_PATTERN_BUILD__", fp_build)
        .replace("__BODY__", "\n".join(" " * 8 + line for line in body))
    )
    ast.parse(source)  # guarantee the generated source is valid Python
    return source
