"""Render a GRISM (WFSS) stage-2 :class:`Recipe` into a two-pass runner script.

Pass 1 reduces each dispersed frame rate -> 2b (flag_outlier -> assign_wcs ->
WFSS master-sky -> flat) and collects a downsampled, trace-masked residual grid
per (module, dispersion direction). Between passes a sky-residual template is
built for each group; pass 2 scalar-fits and subtracts it (2b -> 2bii). The
template is a sidecar FITS, not a NooBox record; 2bii -> 2b lineage is stamped.

Built by sentinel replacement (brace-heavy code needs no escaping) and validated
with :func:`ast.parse`.
"""

import ast

from noobfriend.cli.reduce._recipe import Recipe, ordered
from noobfriend.cli.reduce._reduce_grism_stage2 import CHAIN

_MASTER_SKY: tuple[str, ...] = (
    "_mask = grism_trace_mask("
    "model.data, model.dq, dispersion_axis=_dispersion_axis(book)"
    ")",
    "_bs = BackgroundStep()",
    '_bkg = _bs.get_reference_file(model, "bkg")',
    '_wl = _bs.get_reference_file(model, "wavelengthrange")',
    "model = subtract_wfss_bkg(",
    "    model, _bkg, _wl, mmag_extract=None, user_mask=~_mask,",
    "    rescaler_kwargs={",
    '        "p": _bs.wfss_outlier_percent,',
    '        "maxiter": _bs.wfss_maxiter,',
    '        "delta_rms_thresh": _bs.wfss_rms_stop / 100,',
    "    },",
    ")",
    'if model.meta.cal_step.bkg_subtract != "FAILED":',
    '    model.meta.cal_step.bkg_subtract = "COMPLETE"',
)

_TEMPLATE = '''"""Grism (WFSS) reduction runner generated by `noobfriend reduce gen`.

Two-pass: rate -> 2b per frame, then a per-(module, direction) sky-residual
template is built and subtracted 2b -> 2bii. Run where the NooBox product
locations open locally (e.g. on the data server):

    python <this_script.py>
"""

from __future__ import annotations

import fnmatch
import os
import tempfile
from io import BytesIO
from pathlib import Path

from astropy.io import fits

from noobfriend.core.env import get_settings, stage_path_var

__MUTE_BLOCK__get_settings()  # load .env into os.environ (CRDS, stage paths, NOOBOX_PATH)

from noobfriend.core.display import track
from noobfriend.core.io import write_bytes
from noobfriend.navigation import NooBook, NooBox
__REDUCTION_IMPORT__
import jwst.datamodels as _dm
__JWST_IMPORTS__

STAGE_IN = "__STAGE_IN__"
SELECT = __SELECT__
OUTPUT_NOOBOX = __OUTPUT_NOOBOX__
DO_TEMPLATE = __DO_TEMPLATE__
SCALAR = __SCALAR__
DOWNSAMPLE = __DOWNSAMPLE__
SMOOTH_SIGMA = __SMOOTH_SIGMA__
STAGE_2B = "__STAGE_2B__"
STAGE_2BII = "__STAGE_2BII__"
TEMPLATE_DIR = Path("grism_templates")  # sidecar templates (not NooBox records)


def _keep(book) -> bool:
    """Whether ``book`` matches the recipe selection (scalar pupil/filter/detector)."""
    for field, crit in SELECT.items():
        value = getattr(book, field)
        if isinstance(crit, str):
            if value is None or not fnmatch.fnmatch(str(value), crit):
                return False
        elif crit is not None and value not in crit:
            return False
    return True


def _out_location(book, stage: str) -> str:
    """Compose <NOOB_SERVER>:<STAGE_<stage>_PATH>/<exposure-stem>_<stage>.fits."""
    directory = os.getenv(stage_path_var(stage))
    if directory is None:
        raise RuntimeError(f"{stage_path_var(stage)} is unset in the environment.")
    stem = os.path.basename(book.location)
    for ext in (".fits.gz", ".fits"):
        if stem.endswith(ext):
            stem = stem[: -len(ext)]
            break
    stem = stem.rsplit("_", 1)[0]  # drop the input product suffix
    host = get_settings().server_host()
    base = f"{host}:{directory}" if host else directory
    return base.rstrip("/") + "/" + f"{stem}_{stage}.fits"


def _save_bytes(model, stage: str) -> bytes:
    """Serialise ``model`` to bytes through a temp file (jwst save needs a path)."""
    with tempfile.NamedTemporaryFile(suffix=f"_{stage}.fits", delete=False) as handle:
        tmp = handle.name
    try:
        model.save(tmp)
        return Path(tmp).read_bytes()
    finally:
        os.unlink(tmp)


def _group_key(book) -> tuple[str, str]:
    """Return the (module, dispersion-direction) key a template is built per."""
    detector = book.detector or ""
    module = detector[3].upper() if detector.startswith("nrc") and len(detector) > 3 else "?"
    pupil = book.pupil or ""
    direction = pupil[-1] if pupil.startswith("GRISM") else "R"
    return module, direction


def _dispersion_axis(book) -> str:
    """Return the detector-axis direction used by the grism trace mask."""
    pupil = (book.pupil or "").upper()
    if pupil == "GRISMR":
        return "x"
    if pupil == "GRISMC":
        return "y"
    raise ValueError(f"Unsupported grism pupil for trace masking: {book.pupil!r}.")


def _save_template(group: tuple[str, str], template, nframes: int) -> None:
    """Write a per-group sky-residual template as a sidecar FITS."""
    module, direction = group
    TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)
    hdu = fits.PrimaryHDU(template.astype("float32"))
    hdu.header["MODULE"] = module
    hdu.header["DISPDIR"] = direction
    hdu.header["NFRAMES"] = nframes
    hdu.writeto(TEMPLATE_DIR / f"skytemplate_mod{module}_{direction}.fits", overwrite=True)


def main(output_noobox_path: str | None = None) -> None:
    box = NooBox.load()
    out_box = box if output_noobox_path is None else NooBox()
    grids: dict[tuple[str, str], list] = {}
    produced: list[tuple[str, tuple[str, str]]] = []

    # -- pass 1: rate -> 2b, collect per-group residual grids -----------------
    for book in track(box.select(stage=STAGE_IN), f"Grism pass 1 {STAGE_IN}->{STAGE_2B}"):
        if not book.is_probed:
            book = book.probe()
            out_box.add(book)
        if not _keep(book):
            continue
        model = _dm.open(fits.open(BytesIO(book.read_bytes())))
        parent = book
__PASS1_BODY__
        _loc = _out_location(book, STAGE_2B)
        _raw = _save_bytes(model, STAGE_2B)
        write_bytes(_loc, _raw)
        b2 = NooBook.from_file(_loc, STAGE_2B, parents=[parent], raw=_raw)
        out_box.add(b2)
        if DO_TEMPLATE:
            gmask = grism_trace_mask(
                model.data, model.dq, dispersion_axis=_dispersion_axis(b2)
            )
            grids.setdefault(_group_key(b2), []).append(
                sky_residual_grid(model.data, gmask, factor=DOWNSAMPLE)
            )
            produced.append((b2.id, _group_key(b2)))
        model.close()

    # -- build templates, then pass 2: 2b -> 2bii -----------------------------
    if DO_TEMPLATE:
        templates: dict[tuple[str, str], object] = {}
        for group, group_grids in grids.items():
            shape = (group_grids[0].shape[0] * DOWNSAMPLE, group_grids[0].shape[1] * DOWNSAMPLE)
            templates[group] = combine_sky_template(group_grids, shape, smooth_sigma=SMOOTH_SIGMA)
            _save_template(group, templates[group], len(group_grids))
        for book_id, group in track(produced, f"Grism pass 2 {STAGE_2B}->{STAGE_2BII}"):
            b2 = out_box.get(book_id)
            model = _dm.open(fits.open(BytesIO(b2.read_bytes())))
            tmask = grism_trace_mask(
                model.data, model.dq, dispersion_axis=_dispersion_axis(b2)
            )
            model.data, model.err, model.dq = subtract_sky_template(
                model.data, model.err, model.dq, templates[group], mask=tmask, scalar=SCALAR
            )
            _loc = _out_location(b2, STAGE_2BII)
            _raw = _save_bytes(model, STAGE_2BII)
            write_bytes(_loc, _raw)
            out_box.add(NooBook.from_file(_loc, STAGE_2BII, parents=[b2], raw=_raw))
            model.close()

    out_box.save(output_noobox_path)


if __name__ == "__main__":
    main(OUTPUT_NOOBOX)
'''


def render(recipe: Recipe) -> str:
    """Return the two-pass grism runner-script source (validated by ``ast.parse``)."""
    steps = ordered(CHAIN, recipe.steps)
    pass1_steps = [(spec, cfg) for spec, cfg in steps if spec.name != "template_bkg"]
    do_template = any(spec.name == "template_bkg" for spec, _ in steps)

    save = {name: cfg.save_as for name, cfg in recipe.steps.items() if cfg.save_as}
    stage_2b = save.get("flat", "2b")
    stage_2bii = save.get("template_bkg", "2bii")

    # The trace-mask / template primitives are referenced in the always-present
    # two-pass scaffold (gated at runtime by DO_TEMPLATE), so import them
    # unconditionally; only the optional flag-outlier step is conditional.
    reduction_names = [
        "combine_sky_template",
        "grism_trace_mask",
        "sky_residual_grid",
        "subtract_sky_template",
    ]
    reduction_names.extend(spec.custom for spec, _ in pass1_steps if spec.custom)
    reduction_import = (
        f"from noobfriend.reduction import {', '.join(sorted(reduction_names))}"
    )

    jwst_imports = [
        f"from {spec.jwst.rsplit('.', 1)[0]} import {spec.jwst.rsplit('.', 1)[1]}"
        for spec, _ in pass1_steps
        if spec.jwst
    ]
    if any(spec.name == "master_sky" for spec, _ in pass1_steps):
        jwst_imports += [
            "from jwst.background import BackgroundStep",
            "from jwst.background.background_step import subtract_wfss_bkg",
        ]

    pass1: list[str] = []
    for spec, _ in pass1_steps:
        if spec.custom:
            pass1.append(
                f"model.data, model.err, model.dq = "
                f"{spec.custom}(model.data, model.err, model.dq)"
            )
        elif spec.name == "master_sky":
            pass1 += list(_MASTER_SKY)
        else:
            cls = spec.jwst.rsplit(".", 1)[1]
            pass1.append(f"model = {cls}.call(model)")
    if not pass1:
        pass1.append(
            "# all pass-1 processing steps are skipped; the input model is saved as-is"
        )

    select = {
        field: value
        for field in ("pupil", "filter", "detector")
        if (value := getattr(recipe.select, field)) is not None
    }
    mute_block = (
        "import logging\n\n"
        "logging.disable(logging.WARNING)  "
        "# silence jwst / CRDS / stpipe INFO+WARNING chatter\n\n"
        if recipe.mute_jwst
        else ""
    )

    source = (
        _TEMPLATE.replace("__REDUCTION_IMPORT__", reduction_import)
        .replace("__JWST_IMPORTS__", "\n".join(sorted(jwst_imports)))
        .replace("__MUTE_BLOCK__", mute_block)
        .replace("__STAGE_IN__", recipe.select.stage)
        .replace("__SELECT__", repr(select))
        .replace("__OUTPUT_NOOBOX__", repr(recipe.output_noobox))
        .replace("__DO_TEMPLATE__", repr(do_template))
        .replace("__SCALAR__", repr(recipe.grism.scalar))
        .replace("__DOWNSAMPLE__", repr(recipe.grism.downsample))
        .replace("__SMOOTH_SIGMA__", repr(recipe.grism.smooth_sigma))
        .replace("__STAGE_2B__", stage_2b)
        .replace("__STAGE_2BII__", stage_2bii)
        .replace("__PASS1_BODY__", "\n".join(" " * 8 + line for line in pass1))
    )
    ast.parse(source)  # guarantee the generated source is valid Python
    return source
