"""Render a :class:`~noobfriend.cli.reduce._recipe.Recipe` into a runner script.

The generated script is the explicit, editable reduction chain (step parameters
live in the calls, not the recipe). At run time it loads the NooBox, probes every
input-stage book (back-filling the probed copy), reduces the selected ones
through the chain, saves each ``save_as`` product and registers it with explicit
lineage (``NooBook.from_file(parents=...)``), then writes the manifest.

The source is built by sentinel replacement (not ``str.format``) so the
brace-heavy generated code needs no escaping, and validated with
:func:`ast.parse` before it is returned.
"""

import ast

from noobfriend.cli.reduce._recipe import Recipe

_TEMPLATE = '''"""Reduction runner generated by `noobfriend reduce gen` -- edit step params here.

Run where the NooBox product locations open locally (e.g. on the data server):

    python <this_script.py>

The updated manifest goes to OUTPUT_NOOBOX below (set from the recipe); when it
is None the input manifest (NOOBOX_PATH) is updated in place. Give each parallel
shard its own output_noobox in the recipe and merge them afterwards.
"""

from __future__ import annotations

import fnmatch
import os
import tempfile
from io import BytesIO
from pathlib import Path

from astropy.io import fits

from noobfriend.core.env import get_settings, stage_path_var

get_settings()  # load .env into os.environ (CRDS, stage paths, NOOBOX_PATH)

from noobfriend.core.display import track
from noobfriend.core.io import write_bytes
from noobfriend.navigation import NooBook, NooBox
__REDUCTION_IMPORT__
import jwst.datamodels as _dm
__JWST_IMPORTS__

STAGE_IN = "__STAGE_IN__"
SELECT = __SELECT__
OUTPUT_NOOBOX = __OUTPUT_NOOBOX__


def _keep(book) -> bool:
    """Whether ``book`` matches the recipe selection (scalar pupil/filter/detector)."""
    for field, crit in SELECT.items():
        value = getattr(book, field)
        if isinstance(crit, str):
            if value is None or not fnmatch.fnmatch(str(value), crit):
                return False
        elif crit is not None and value not in crit:
            return False
    return True


def _out_location(book, stage: str) -> str:
    """Compose <NOOB_SERVER>:<STAGE_<stage>_PATH>/<exposure-stem>_<stage>.fits.

    Remote (a ``host:path`` spec) when NOOB_SERVER names a host, so write_bytes
    uploads over SSH; local otherwise. Parent directories are created by
    write_bytes, not here.
    """
    directory = os.getenv(stage_path_var(stage))
    if directory is None:
        raise RuntimeError(f"{stage_path_var(stage)} is unset in the environment.")
    stem = os.path.basename(book.location)
    for ext in (".fits.gz", ".fits"):
        if stem.endswith(ext):
            stem = stem[: -len(ext)]
            break
    stem = stem.rsplit("_", 1)[0]  # drop the input product suffix
    host = get_settings().server_host()
    base = f"{host}:{directory}" if host else directory
    return base.rstrip("/") + "/" + f"{stem}_{stage}.fits"


def _save_bytes(model, stage: str) -> bytes:
    """Serialise ``model`` to bytes through a temp file (jwst save needs a path)."""
    with tempfile.NamedTemporaryFile(suffix=f"_{stage}.fits", delete=False) as handle:
        tmp = handle.name
    try:
        model.save(tmp)
        return Path(tmp).read_bytes()
    finally:
        os.unlink(tmp)


def main(output_noobox_path: str | None = None) -> None:
    box = NooBox.load()
    out_box = box if output_noobox_path is None else NooBox()
    for book in track(box.select(stage=STAGE_IN), f"Reducing {STAGE_IN}"):
        if not book.is_probed:
            book = book.probe()
            out_box.add(book)  # back-fill the probed copy into the manifest
        if not _keep(book):
            continue
        # bytes via the NooBox store: remote-capable and reuses the probe fetch.
        model = _dm.open(fits.open(BytesIO(book.read_bytes())))
        parent = book
__BODY__
        model.close()
    out_box.save(output_noobox_path)


if __name__ == "__main__":
    main(OUTPUT_NOOBOX)
'''


def render(recipe: Recipe) -> str:
    """Return the runner-script source for ``recipe`` (validated by ``ast.parse``)."""
    steps = recipe.ordered()

    customs = sorted({spec.custom for spec, _ in steps if spec.custom})
    reduction_import = (
        f"from noobfriend.reduction import {', '.join(customs)}" if customs else ""
    )
    jwst_imports = sorted(
        {
            f"from {spec.jwst.rsplit('.', 1)[0]} import {spec.jwst.rsplit('.', 1)[1]}"
            for spec, _ in steps
            if spec.jwst
        }
    )

    select = {
        field: value
        for field in ("pupil", "filter", "detector")
        if (value := getattr(recipe.select, field)) is not None
    }

    body: list[str] = []
    for spec, cfg in steps:
        if spec.custom:
            body.append(
                f"model.data, model.err, model.dq = "
                f"{spec.custom}(model.data, model.err, model.dq)"
            )
        else:
            cls = spec.jwst.rsplit(".", 1)[1]
            body.append(f"model = {cls}.call(model)")
        if cfg.save_as:
            stage = cfg.save_as
            body += [
                f"_loc = _out_location(book, {stage!r})",
                f"_raw = _save_bytes(model, {stage!r})",
                "write_bytes(_loc, _raw)",
                f"parent = NooBook.from_file(_loc, {stage!r}, parents=[parent], raw=_raw)",
                "out_box.add(parent)",
            ]

    source = (
        _TEMPLATE.replace("__REDUCTION_IMPORT__", reduction_import)
        .replace("__JWST_IMPORTS__", "\n".join(jwst_imports))
        .replace("__STAGE_IN__", recipe.select.stage)
        .replace("__SELECT__", repr(select))
        .replace("__OUTPUT_NOOBOX__", repr(recipe.output_noobox))
        .replace("__BODY__", "\n".join(" " * 8 + line for line in body))
    )
    ast.parse(source)  # guarantee the generated source is valid Python
    return source
