"""Render a CLEAR (imaging) stage-3 :class:`Recipe` into a mosaicking runner.

Stage-3 is group-based, not per-frame: the generated script loads the NooBox,
partitions the selected 2bi cal frames into mosaics by ``[stage3].group_by``,
and for each group runs a field-level prep (``TweakRegStep`` with cleaned image
catalogs + a PM-propagated GAIA ``abs_refcat`` -> ``SkyMatchStep`` ->
``OutlierDetectionStep``) before drizzling onto a unified, tiled output grid
(``ResampleStep`` per tile -> 3a). Each tile product stamps the cal books it
drizzled as its parents, so the many-to-one lineage is recorded explicitly.

Built by sentinel replacement (brace-heavy generated code needs no escaping) and
validated with :func:`ast.parse` before it is returned.
"""

import ast

from noobfriend.cli.reduce._recipe import Recipe

_TEMPLATE = '''"""Stage-3 mosaicking runner generated by `noobfriend reduce gen` -- edit params here.

Group the selected stage-__STAGE_IN__ cal frames into mosaics, align / sky-match /
outlier-flag each group, then drizzle it onto a unified, tiled output grid. Run
where the NooBox product locations open locally (e.g. on the data server):

    python <this_script.py>

The updated manifest goes to OUTPUT_NOOBOX (set from the recipe); when None the
input manifest (NOOBOX_PATH) is updated in place.
"""

from __future__ import annotations

import fnmatch
import os
import shutil
import tempfile
from pathlib import Path

import numpy as np

from noobfriend.core.env import get_settings, stage_path_var

__MUTE_BLOCK__get_settings()  # load .env into os.environ (CRDS, stage paths, NOOBOX_PATH)

from noobfriend.core.display import track
from noobfriend.core.imgutils import build_catalog
from noobfriend.core.io import write_bytes
from noobfriend.navigation import Footprint, NooBook, NooBox
from noobfriend.reduction import (
    build_reference,
    field_grid,
    select_point_sources,
    tile_grid,
    tile_members,
    tile_resample_params,
    to_tweakreg_catalog,
)
from jwst.datamodels import ModelContainer, ModelLibrary
from jwst.outlier_detection import OutlierDetectionStep
from jwst.resample import ResampleStep
from jwst.skymatch import SkyMatchStep
from jwst.tweakreg import TweakRegStep

STAGE_IN = "__STAGE_IN__"
STAGE_OUT = "__STAGE_OUT__"
SELECT = __SELECT__
GROUP_BY = __GROUP_BY__
OUTPUT_NOOBOX = __OUTPUT_NOOBOX__
PIXEL_SCALE_SW = __PIXEL_SCALE_SW__
PIXEL_SCALE_LW = __PIXEL_SCALE_LW__
ALIGN_TO_ROLL = __ALIGN_TO_ROLL__
TILE_SIZE = __TILE_SIZE__
TILE_OVERLAP = __TILE_OVERLAP__
MIN_COVERAGE = __MIN_COVERAGE__
OBS_EPOCH = __OBS_EPOCH__
STAR_FWHM_PX = __STAR_FWHM_PX__
MINOBJ = __MINOBJ__
ABS_MINOBJ = __ABS_MINOBJ__
PIXFRAC = __PIXFRAC__
IN_MEMORY = __IN_MEMORY__
DO_ALIGN = __DO_ALIGN__
DO_SKYMATCH = __DO_SKYMATCH__
DO_OUTLIER = __DO_OUTLIER__
WORK_DIR = Path(__WORK_DIR__)  # per-group catalogs / refcats (sidecars, not records)
CLEAN_WORK = __CLEAN_WORK__


def _keep(book) -> bool:
    """Whether ``book`` matches the recipe selection (scalar pupil/filter/detector)."""
    for field, crit in SELECT.items():
        value = getattr(book, field)
        if isinstance(crit, str):
            if value is None or not fnmatch.fnmatch(str(value), crit):
                return False
        elif crit is not None and value not in crit:
            return False
    return True


def _group_key(book) -> tuple[str, ...]:
    """Return the mosaic identity of ``book`` from the GROUP_BY fields."""
    parts: list[str] = []
    for field in GROUP_BY:
        value = getattr(book, field)
        parts.append("+".join(value) if isinstance(value, tuple) else str(value))
    return tuple(parts)


def _pixel_scale(gbooks) -> float:
    """Long-wave (nrc?long) or short-wave output scale for the group's channel."""
    detector = gbooks[0].detector or ""
    return PIXEL_SCALE_LW if detector.endswith("long") else PIXEL_SCALE_SW


def _scale_token(scale: float) -> str:
    """Filename-safe scale token, e.g. 0.025 -> 's0p025'."""
    return "s" + f"{scale:.3f}".replace(".", "p")


def _materialize(gbooks, cal_dir: Path) -> list[str]:
    """Write each (possibly remote) cal book to a local file; return the paths.

    A file-backed association is required for an on-disk ModelLibrary (jwst will
    not stream from in-memory models), so the group's frames are fetched through
    the NooBox store once and staged locally here.
    """
    cal_dir.mkdir(parents=True, exist_ok=True)
    paths: list[str] = []
    for book in gbooks:
        path = cal_dir / os.path.basename(book.location)
        path.write_bytes(book.read_bytes())
        paths.append(str(path))
    return paths


def _asn(paths: list[str]) -> dict:
    """Build a minimal jwst association over the staged cal files."""
    return {
        "asn_id": "stage3",
        "asn_pool": "none",
        "products": [
            {
                "name": "stage3",
                "members": [{"expname": p, "exptype": "science"} for p in paths],
            }
        ],
    }


def _corners(model) -> np.ndarray:
    """Return the model's on-sky corners as an ``(N, 2)`` ra/dec array (deg)."""
    footprint = Footprint.from_wcs(model.meta.wcs, model.data.shape)
    return np.asarray(footprint.corners, dtype=float)


def _library_corners(library) -> list[np.ndarray]:
    """Borrow each model in turn and collect its footprint corners."""
    corners: list[np.ndarray] = []
    with library:
        for index, model in enumerate(library):
            corners.append(_corners(model))
            library.shelve(model, index, modify=False)
    return corners


def _field_cone(corners_list: list[np.ndarray]) -> tuple[float, float, float]:
    """Return a (ra, dec, radius) cone enclosing every footprint (degrees)."""
    pts = np.vstack(corners_list)
    ra0 = float(np.rad2deg(np.arctan2(
        np.sin(np.deg2rad(pts[:, 0])).mean(), np.cos(np.deg2rad(pts[:, 0])).mean()
    )) % 360.0)
    dec0 = float(pts[:, 1].mean())
    cos_dec = np.cos(np.deg2rad(dec0))
    dra = (pts[:, 0] - ra0) * cos_dec
    radius = float(np.max(np.hypot(dra, pts[:, 1] - dec0))) * 1.1
    return ra0, dec0, radius


def _align_inputs(library, work: Path) -> tuple[Path, list[np.ndarray]]:
    """Build per-model point-source catalogs + a catfile; return it with corners.

    One borrow pass over the library: detect + select point sources for each
    frame (written as an ecsv keyed by the frame's filename, the form tweakreg's
    ``catfile`` matches on) and collect the pre-alignment corners used to size
    the GAIA cone.
    """
    work.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    corners: list[np.ndarray] = []
    with library:
        for index, model in enumerate(library):
            cat = build_catalog(
                np.asarray(model.data),
                fwhm=STAR_FWHM_PX,
                nsigma=5.0,
                err=np.asarray(model.err),
                pixel_to_world=lambda x, y, w=model.meta.wcs: w(
                    np.asarray(x), np.asarray(y)
                ),
            )
            stars = select_point_sources(cat)
            catpath = work / f"{Path(model.meta.filename).stem}_stars.ecsv"
            to_tweakreg_catalog(stars).write(catpath, overwrite=True)
            lines.append(f"{model.meta.filename} {catpath.resolve()}")
            corners.append(_corners(model))
            library.shelve(model, index, modify=False)
    catfile = work / "catfile.txt"
    catfile.write_text("\\n".join(lines) + "\\n")
    return catfile, corners


def _abs_refcat(corners_list: list[np.ndarray], work: Path) -> Path:
    """Build + write the GAIA absolute reference, trimmed to the footprints.

    The cone query over-covers by ~2x, so the reference is filtered to sources
    actually inside the frames' footprints -- the honest on-pixel anchor set.
    """
    work.mkdir(parents=True, exist_ok=True)
    ra0, dec0, radius = _field_cone(corners_list)
    refcat = build_reference(ra0, dec0, radius, OBS_EPOCH, footprints=corners_list)
    path = work / "abs_refcat.ecsv"
    refcat.write(path, overwrite=True)
    return path


def _save_bytes(model, stage: str) -> bytes:
    """Serialise ``model`` to bytes through a temp file (jwst save needs a path)."""
    with tempfile.NamedTemporaryFile(suffix=f"_{stage}.fits", delete=False) as handle:
        tmp = handle.name
    try:
        model.save(tmp)
        return Path(tmp).read_bytes()
    finally:
        os.unlink(tmp)


def _out_location(program_id: str, tag: str, tile, scale: float, stage: str) -> str:
    """Compose <NOOB_SERVER>:<STAGE_<stage>_PATH>/jw<pid>_<tag>_t<iy>x<ix>_s<scale>_<stage>.fits.

    The tile carries no per-exposure identity (its inputs are recorded in
    parent_ids, not the name); the tag is the GROUP_BY values, the zero-padded
    t<row>x<col> the tile position and s<scale> the output pixel scale, so
    products of different scales never collide and sort/group cleanly.
    """
    directory = os.getenv(stage_path_var(stage))
    if directory is None:
        raise RuntimeError(f"{stage_path_var(stage)} is unset in the environment.")
    name = (
        f"jw{program_id}_{tag}_t{tile.iy:02d}x{tile.ix:02d}_"
        f"{_scale_token(scale)}_{stage}.fits"
    )
    host = get_settings().server_host()
    base = f"{host}:{directory}" if host else directory
    return base.rstrip("/") + "/" + name


def main(output_noobox_path: str | None = None) -> None:
    box = NooBox.load()
    out_box = box if output_noobox_path is None else NooBox()

    books = []
    for book in track(box.select(stage=STAGE_IN), f"Probing {STAGE_IN}"):
        if not book.is_probed:
            book = book.probe()
            out_box.add(book)  # back-fill the probed copy into the manifest
        if _keep(book):
            books.append(book)

    groups: dict[tuple[str, ...], list] = {}
    for book in books:
        groups.setdefault(_group_key(book), []).append(book)

    for gkey, gbooks in track(list(groups.items()), "Mosaicking groups"):
        tag = "_".join(gkey)
        work = WORK_DIR / tag
        # Stage the group's frames locally and wrap them in a (possibly on-disk)
        # ModelLibrary -- the stage-3 steps return a library, not the input, and
        # only an on-disk library bounds memory on large fields (IN_MEMORY=False).
        paths = _materialize(gbooks, work / "cal")
        library = ModelLibrary(_asn(paths), on_disk=not IN_MEMORY)

        if DO_ALIGN:
            catfile, pre_corners = _align_inputs(library, work)
            absref = _abs_refcat(pre_corners, work)
            library = TweakRegStep.call(
                library,
                use_custom_catalogs=True,
                catfile=str(catfile),
                abs_refcat=str(absref),
                minobj=MINOBJ,
                abs_minobj=ABS_MINOBJ,
            )
        if DO_SKYMATCH:
            library = SkyMatchStep.call(library, in_memory=IN_MEMORY)
        if DO_OUTLIER:
            library = OutlierDetectionStep.call(library, in_memory=IN_MEMORY)

        scale = _pixel_scale(gbooks)
        corners = _library_corners(library)
        field = field_grid(corners, scale, rotation="auto" if ALIGN_TO_ROLL else 0.0)
        program_id = gbooks[0].program_id
        for tile in tile_grid(field, target_size=TILE_SIZE, overlap=TILE_OVERLAP):
            members, coverage = tile_members(field, tile, corners)
            if not members or coverage < MIN_COVERAGE:
                continue
            # Resample the member subset (in memory -- the subset is small and
            # the output is one bounded tile, so IN_MEMORY governs the prep, not
            # this; an on-disk library cannot wrap an in-memory model list).
            with library:
                borrowed = [library.borrow(i) for i in members]
                resampled = ResampleStep.call(
                    ModelContainer(borrowed),
                    pixfrac=PIXFRAC,
                    in_memory=True,
                    **tile_resample_params(field, tile),
                )
                for index, model in zip(members, borrowed):
                    library.shelve(model, index, modify=False)
            loc = _out_location(program_id, tag, tile, scale, STAGE_OUT)
            raw = _save_bytes(resampled, STAGE_OUT)
            write_bytes(loc, raw)
            out_box.add(
                NooBook.from_file(
                    loc, STAGE_OUT, parents=[gbooks[i] for i in members], raw=raw
                )
            )
            resampled.close()

        if CLEAN_WORK:
            shutil.rmtree(work, ignore_errors=True)

    out_box.save(output_noobox_path)


if __name__ == "__main__":
    main(OUTPUT_NOOBOX)
'''


def render(recipe: Recipe) -> str:
    """Return the stage-3 mosaicking runner source (validated by ``ast.parse``)."""
    skipped = {name for name, cfg in recipe.steps.items() if cfg.skip}
    do_align = "align" not in skipped
    do_skymatch = "skymatch" not in skipped
    do_outlier = "outlier" not in skipped

    save = {name: cfg.save_as for name, cfg in recipe.steps.items() if cfg.save_as}
    stage_out = save.get("resample", "3a")

    select = {
        field: value
        for field in ("pupil", "filter", "detector")
        if (value := getattr(recipe.select, field)) is not None
    }
    mute_block = (
        "import logging\n\n"
        "logging.disable(logging.WARNING)  "
        "# silence jwst / CRDS / stpipe INFO+WARNING chatter\n\n"
        if recipe.mute_jwst
        else ""
    )
    s3 = recipe.stage3

    source = (
        _TEMPLATE.replace("__MUTE_BLOCK__", mute_block)
        .replace("__STAGE_IN__", recipe.select.stage)
        .replace("__STAGE_OUT__", stage_out)
        .replace("__SELECT__", repr(select))
        .replace("__GROUP_BY__", repr(s3.group_by))
        .replace("__OUTPUT_NOOBOX__", repr(recipe.output_noobox))
        .replace("__PIXEL_SCALE_SW__", repr(s3.pixel_scale_sw))
        .replace("__PIXEL_SCALE_LW__", repr(s3.pixel_scale_lw))
        .replace("__ALIGN_TO_ROLL__", repr(s3.align_to_roll))
        .replace("__TILE_SIZE__", repr(s3.tile_size))
        .replace("__TILE_OVERLAP__", repr(s3.tile_overlap))
        .replace("__MIN_COVERAGE__", repr(s3.min_coverage))
        .replace("__OBS_EPOCH__", repr(s3.obs_epoch))
        .replace("__STAR_FWHM_PX__", repr(s3.star_fwhm_px))
        .replace("__MINOBJ__", repr(s3.minobj))
        .replace("__ABS_MINOBJ__", repr(s3.abs_minobj))
        .replace("__PIXFRAC__", repr(s3.pixfrac))
        .replace("__IN_MEMORY__", repr(s3.in_memory))
        .replace("__WORK_DIR__", repr(s3.work_dir))
        .replace("__CLEAN_WORK__", repr(s3.clean_work))
        .replace("__DO_ALIGN__", repr(do_align))
        .replace("__DO_SKYMATCH__", repr(do_skymatch))
        .replace("__DO_OUTLIER__", repr(do_outlier))
    )
    ast.parse(source)  # guarantee the generated source is valid Python
    return source
