"""Render a CLEAR (imaging) stage-2 :class:`Recipe` into a per-frame runner script.

The generated script is the explicit, editable reduction chain (step parameters
live in the calls, not the recipe). At run time it loads the NooBox, probes every
input-stage book, reduces the selected ones through the chain, saves each
``save_as`` product with explicit lineage, then writes the manifest.

The source is built by sentinel replacement (not ``str.format``) so the
brace-heavy generated code needs no escaping, and validated with
:func:`ast.parse` before it is returned.
"""

import ast

from noobfriend.cli.reduce._recipe import Recipe, ordered
from noobfriend.cli.reduce._reduce_clear_stage2 import CHAIN

_TEMPLATE = '''"""Reduction runner generated by `noobfriend reduce gen` -- edit step params here.

Run where the NooBox product locations open locally (e.g. on the data server):

    python <this_script.py>

The updated manifest goes to OUTPUT_NOOBOX below (set from the recipe); when it
is None the input manifest (NOOBOX_PATH) is updated in place. Give each parallel
shard its own output_noobox in the recipe and merge them afterwards.
"""

from __future__ import annotations

import fnmatch
import os
import tempfile
from pathlib import Path

from noobfriend.core.env import get_settings, stage_path_var, to_canonical, to_local

__MUTE_BLOCK__get_settings()  # load .env into os.environ (CRDS, stage paths, NOOBOX_PATH)

from noobfriend.core.display import track
from noobfriend.core.io import write_bytes
from noobfriend.navigation import NooBook, NooBox
__REDUCTION_IMPORT__
import jwst.datamodels as _dm
__JWST_IMPORTS__

STAGE_IN = "__STAGE_IN__"
SELECT = __SELECT__
OUTPUT_NOOBOX = __OUTPUT_NOOBOX__


def _keep(book) -> bool:
    """Whether ``book`` matches the recipe selection (scalar pupil/filter/detector)."""
    for field, crit in SELECT.items():
        value = getattr(book, field)
        if isinstance(crit, str):
            if value is None or not fnmatch.fnmatch(str(value), crit):
                return False
        elif crit is not None and value not in crit:
            return False
    return True


def _out_location(book, stage: str) -> str:
    """Canonical <host>:<server_path>/<stem>_<stage>.fits for the product.

    ``to_canonical`` rewrites a locally-mounted path back to its portable
    ``host:server_path`` form so the NooBox records the server location, not this
    machine's mount point; an already-remote or unmounted-local path is returned
    as composed.
    """
    directory = os.getenv(stage_path_var(stage))
    if directory is None:
        raise RuntimeError(f"{stage_path_var(stage)} is unset in the environment.")
    stem = os.path.basename(book.location)
    for ext in (".fits.gz", ".fits"):
        if stem.endswith(ext):
            stem = stem[: -len(ext)]
            break
    stem = stem.rsplit("_", 1)[0]  # drop the input product suffix
    host = get_settings().server_host()
    base = f"{host}:{directory}" if host else directory
    return to_canonical(base.rstrip("/") + "/" + f"{stem}_{stage}.fits")


def _open_model(raw: bytes):
    """Open a JWST datamodel from bytes without passing a deprecated HDUList."""
    with tempfile.NamedTemporaryFile(suffix=".fits", delete=False) as handle:
        tmp = handle.name
        handle.write(raw)
    try:
        return _dm.open(tmp)
    finally:
        os.unlink(tmp)


def _open_input(book):
    """Open a book's product as a datamodel, directly when it is locally mounted.

    ``to_local`` returns a real path when the book's (possibly canonical
    ``host:path``) location resolves on this machine -- opened straight, with no
    temp file and no deprecated bytes path; otherwise the bytes are fetched
    (remote-capable, cached) and opened through a temp file.
    """
    local = to_local(book.location)
    if local is not None:
        return _dm.open(str(local))
    return _open_model(book.read_bytes())


def _save_bytes(model, stage: str) -> bytes:
    """Serialise ``model`` to bytes through a temp file (jwst save needs a path)."""
    with tempfile.NamedTemporaryFile(suffix=f"_{stage}.fits", delete=False) as handle:
        tmp = handle.name
    try:
        model.save(tmp)
        return Path(tmp).read_bytes()
    finally:
        os.unlink(tmp)


def _write_product(model, location: str, stage: str) -> bytes:
    """Write ``model`` to ``location`` and return its bytes for the manifest.

    A locally-mounted ``location`` is written straight to the mount (no temp file,
    no SSH); a remote one is serialised to a temp file and uploaded. The returned
    bytes seed ``NooBook.from_file`` so it need not re-read the product.
    """
    dest = to_local(location)
    if dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        model.save(str(dest))
        return dest.read_bytes()
    raw = _save_bytes(model, stage)
    write_bytes(location, raw)
    return raw


def main(output_noobox_path: str | None = None) -> None:
    box = NooBox.load()
    out_box = box if output_noobox_path is None else NooBox()
    for book in track(box.select(stage=STAGE_IN), f"Reducing {STAGE_IN}"):
        if not book.is_probed:
            book = book.probe()
            out_box.add(book)  # back-fill the probed copy into the manifest
        if not _keep(book):
            continue
        model = _open_input(book)
        parent = book
__BODY__
        model.close()
    out_box.save(output_noobox_path)


if __name__ == "__main__":
    main(OUTPUT_NOOBOX)
'''


def render(recipe: Recipe) -> str:
    """Return the runner-script source for ``recipe`` (validated by ``ast.parse``)."""
    steps = ordered(CHAIN, recipe.steps)

    custom_names = {spec.custom for spec, _ in steps if spec.custom}
    reduction_import = (
        f"from noobfriend.reduction.detector import {', '.join(sorted(custom_names))}"
        if custom_names
        else ""
    )
    jwst_imports = sorted(
        {
            f"from {spec.jwst.rsplit('.', 1)[0]} import {spec.jwst.rsplit('.', 1)[1]}"
            for spec, _ in steps
            if spec.jwst
        }
    )

    select = {
        field: value
        for field in ("pupil", "filter", "detector")
        if (value := getattr(recipe.select, field)) is not None
    }

    mute_block = (
        "import logging\n\n"
        "logging.disable(logging.WARNING)  "
        "# silence jwst / CRDS / stpipe INFO+WARNING chatter\n\n"
        if recipe.mute_jwst
        else ""
    )

    body: list[str] = []
    for spec, cfg in steps:
        if spec.custom:
            body.append(
                f"model.data, model.err, model.dq = "
                f"{spec.custom}(model.data, model.err, model.dq)"
            )
        else:
            cls = spec.jwst.rsplit(".", 1)[1]
            body.append(f"model = {cls}.call(model)")
        if cfg.save_as:
            stage = cfg.save_as
            body += [
                f"_loc = _out_location(book, {stage!r})",
                f"_raw = _write_product(model, _loc, {stage!r})",
                f"parent = NooBook.from_file(_loc, {stage!r}, parents=[parent], raw=_raw)",
                "out_box.add(parent)",
            ]

    source = (
        _TEMPLATE.replace("__REDUCTION_IMPORT__", reduction_import)
        .replace("__JWST_IMPORTS__", "\n".join(jwst_imports))
        .replace("__MUTE_BLOCK__", mute_block)
        .replace("__STAGE_IN__", recipe.select.stage)
        .replace("__SELECT__", repr(select))
        .replace("__OUTPUT_NOOBOX__", repr(recipe.output_noobox))
        .replace("__BODY__", "\n".join(" " * 8 + line for line in body))
    )
    ast.parse(source)  # guarantee the generated source is valid Python
    return source
