"""Render a :class:`~noobfriend.cli.reduce._recipe.Recipe` into a runner script.

The generated script is the explicit, editable reduction chain (step parameters
live in the calls, not the recipe). At run time it loads the NooBox, probes every
input-stage book (back-filling the probed copy), reduces the selected ones
through the chain, saves each ``save_as`` product and registers it with explicit
lineage (``NooBook.from_file(parents=...)``), then writes the manifest.

The source is built by sentinel replacement (not ``str.format``) so the
brace-heavy generated code needs no escaping, and validated with
:func:`ast.parse` before it is returned.
"""

import ast

from noobfriend.cli.reduce._recipe import Recipe

_TEMPLATE = '''"""Reduction runner generated by `noobfriend reduce gen` -- edit step params here.

Run where the NooBox product locations open locally (e.g. on the data server):

    python <this_script.py> [OUTPUT_NOOBOX_PATH]

With no argument the input manifest (NOOBOX_PATH) is updated in place; pass a
path to write a separate manifest instead (parallel shards merge those later).
"""

from __future__ import annotations

import argparse
import fnmatch
import os
from io import BytesIO
from pathlib import Path

from astropy.io import fits

from noobfriend.core.env import get_settings, stage_path_var

get_settings()  # load .env into os.environ (CRDS, stage paths, NOOBOX_PATH)

from noobfriend.core.display import track
from noobfriend.navigation import NooBook, NooBox
__REDUCTION_IMPORT__
import jwst.datamodels as _dm
__JWST_IMPORTS__

STAGE_IN = "__STAGE_IN__"
SELECT = __SELECT__


def _keep(book) -> bool:
    """Whether ``book`` matches the recipe selection (scalar pupil/filter/detector)."""
    for field, crit in SELECT.items():
        value = getattr(book, field)
        if isinstance(crit, str):
            if value is None or not fnmatch.fnmatch(str(value), crit):
                return False
        elif crit is not None and value not in crit:
            return False
    return True


def _out_path(book, stage: str) -> str:
    """Build <STAGE_<stage>_PATH>/<exposure-stem>_<stage>.fits for an output."""
    directory = os.getenv(stage_path_var(stage))
    if directory is None:
        raise RuntimeError(f"{stage_path_var(stage)} is unset in the environment.")
    stem = os.path.basename(book.location)
    for ext in (".fits.gz", ".fits"):
        if stem.endswith(ext):
            stem = stem[: -len(ext)]
            break
    stem = stem.rsplit("_", 1)[0]  # drop the input product suffix
    Path(directory).mkdir(parents=True, exist_ok=True)
    return os.path.join(directory, f"{stem}_{stage}.fits")


def main(output_noobox_path: str | None = None) -> None:
    box = NooBox.load()
    out_box = box if output_noobox_path is None else NooBox()
    for book in track(box.select(stage=STAGE_IN), f"Reducing {STAGE_IN}"):
        if not book.is_probed:
            book = book.probe()
            out_box.add(book)  # back-fill the probed copy into the manifest
        if not _keep(book):
            continue
        # bytes via the NooBox store: remote-capable and reuses the probe fetch.
        model = _dm.open(fits.open(BytesIO(book.read_bytes())))
        parent = book
__BODY__
        model.close()
    out_box.save(output_noobox_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run this generated reduction chain.")
    parser.add_argument(
        "--output-noobox",
        metavar="PATH",
        default=None,
        help="Write the updated manifest here instead of in place (NOOBOX_PATH); "
        "use a separate path per shard when running in parallel.",
    )
    main(parser.parse_args().output_noobox)
'''


def render(recipe: Recipe) -> str:
    """Return the runner-script source for ``recipe`` (validated by ``ast.parse``)."""
    steps = recipe.ordered()

    customs = sorted({spec.custom for spec, _ in steps if spec.custom})
    reduction_import = (
        f"from noobfriend.reduction import {', '.join(customs)}" if customs else ""
    )
    jwst_imports = sorted(
        {
            f"from {spec.jwst.rsplit('.', 1)[0]} import {spec.jwst.rsplit('.', 1)[1]}"
            for spec, _ in steps
            if spec.jwst
        }
    )

    select = {
        field: value
        for field in ("pupil", "filter", "detector")
        if (value := getattr(recipe.select, field)) is not None
    }

    body: list[str] = []
    for spec, cfg in steps:
        if spec.custom:
            body.append(
                f"model.data, model.err, model.dq = "
                f"{spec.custom}(model.data, model.err, model.dq)"
            )
        else:
            cls = spec.jwst.rsplit(".", 1)[1]
            body.append(f"model = {cls}.call(model)")
        if cfg.save_as:
            body += [
                f"_out = _out_path(book, {cfg.save_as!r})",
                "model.save(_out)",
                f"parent = NooBook.from_file(_out, {cfg.save_as!r}, parents=[parent])",
                "out_box.add(parent)",
            ]

    source = (
        _TEMPLATE.replace("__REDUCTION_IMPORT__", reduction_import)
        .replace("__JWST_IMPORTS__", "\n".join(jwst_imports))
        .replace("__STAGE_IN__", recipe.select.stage)
        .replace("__SELECT__", repr(select))
        .replace("__BODY__", "\n".join(" " * 8 + line for line in body))
    )
    ast.parse(source)  # guarantee the generated source is valid Python
    return source
