"""Custom reduction steps as a pure, navigation-agnostic method library.

The per-frame stage-2 steps operate on plain ``(data, err, dq)`` numpy arrays
and return the same triple. The stage-3 helpers keep the same purity (no
dependency on :mod:`jwst`, :mod:`stdatamodels`, FITS headers or the navigation
layer) but carry the shapes mosaicking needs instead of pixel triples: footprint
corners in / output geometry out (:mod:`~noobfriend.reduction._tiling`) and
catalogs in / catalogs out (:mod:`~noobfriend.reduction._astrometry`). A
reduction *script* (generated by the CLI and run in a ``jwst`` environment) is
what unwraps datamodels, calls these steps around the official pipeline steps,
and writes the result back.
"""

from noobfriend.reduction._astrometry import (
    GaiaReference,
    ReferenceProvider,
    build_reference,
    clean_gaia,
    query_gaia,
    select_point_sources,
    to_tweakreg_catalog,
    within_footprints,
)
from noobfriend.reduction._background import subtract_background
from noobfriend.reduction._badpixel import flag_outlier_pixels
from noobfriend.reduction._fixed_pattern import (
    combine_fixed_pattern,
    fit_pattern_amplitude,
    fixed_pattern_residual,
    subtract_fixed_pattern,
)
from noobfriend.reduction._oneoverf import subtract_oneoverf
from noobfriend.reduction._sky_template import (
    combine_sky_template,
    fit_template_scalar,
    sky_residual_grid,
    subtract_sky_template,
)
from noobfriend.reduction._tiling import (
    FieldGrid,
    TileSpec,
    field_grid,
    tile_grid,
    tile_members,
    tile_resample_params,
)
from noobfriend.reduction._trace_mask import grism_trace_mask

__all__ = [
    "FieldGrid",
    "GaiaReference",
    "ReferenceProvider",
    "TileSpec",
    "build_reference",
    "clean_gaia",
    "combine_fixed_pattern",
    "combine_sky_template",
    "field_grid",
    "fit_pattern_amplitude",
    "fit_template_scalar",
    "fixed_pattern_residual",
    "flag_outlier_pixels",
    "grism_trace_mask",
    "query_gaia",
    "select_point_sources",
    "sky_residual_grid",
    "subtract_background",
    "subtract_fixed_pattern",
    "subtract_oneoverf",
    "subtract_sky_template",
    "tile_grid",
    "tile_members",
    "tile_resample_params",
    "to_tweakreg_catalog",
    "within_footprints",
]
