"""Custom reduction steps as a pure, navigation-agnostic method library.

Organised by role into one subpackage each; no names are re-exported here --
import from the subpackage that defines them:

- :mod:`~noobfriend.reduction.detector` -- per-frame, mode-agnostic detector
  cleanups on ``(data, err, dq)`` arrays (1/f striping, bad-pixel flagging, 2-D
  background, and the shared source masking they build on).
- :mod:`~noobfriend.reduction.grism` -- WFSS-specific frame helpers (dispersed
  trace masking and the per-(module, direction) sky-residual template).
- :mod:`~noobfriend.reduction.mosaic` -- stage-3 combination helpers that carry
  the shapes mosaicking needs (footprint corners in / output geometry out;
  catalogs in / catalogs out), free of :mod:`jwst` / :mod:`stdatamodels` / FITS.

A reduction *script* (generated by the CLI and run in a ``jwst`` environment) is
what unwraps datamodels, calls these steps around the official pipeline steps,
and writes the result back.
"""
